import type { Metadata } from "next";
import "./globals.css";
import { sahel } from "@/next-persian-fonts/sahel";
import Navbar from "@/components/global/navabr";
import { Toaster } from "react-hot-toast";
import Avatar from "@/components/global/avatar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sahel.className} bg-[#f8fafc] antialiased relative`}>
        {/* SnakeLine with z-index 0 will appear behind other components */}
        <Avatar />
        <div className="relative">
          <Navbar />
        </div>
        <div className="relative z-10">{children}</div>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
